name: build ezquake
#on: [pull_request]
on: [push, pull_request]
jobs:
  windows-build:
#    if: github.repository == 'QW-Group/qwprot'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
       target: [windows-glsl-x64, windows-std-x64, windows-multi-x64]
       include:
         - target: windows-glsl-x64
           config: rls-modern
           platform: x64
         - target: windows-std-x64
           config: rls-classic
           platform: x64
         - target: windows-multi-x64
           config: rls-all
           platform: x64
    steps:
    - name: Checkout qwprot
      uses: actions/checkout@v3
    - name: Checkout ezquake
      uses: actions/checkout@master
      with:
        repository: QW-Group/ezquake-source
        path: ezquake
        submodules: recursive
    - name: Update qwprot in ezquake
      run: |
           cp src/* ./ezquake/src/qwprot/src
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build txt2c
      run: msbuild ezquake\misc\vstudio\txt2c\txt2c.vcxproj -t:rebuild -property:Configuration=Release
    - name: Make dir
      run: mkdir ezquake\.vs
    - name: Copy txt2c
      run: cp ezquake\misc\vstudio\txt2c\.vs\txt2c.exe ezquake\.vs\
    - name: Build ezquake
      run: |
           cd ezquake
           msbuild ezQuake.vcxproj -t:rebuild -property:Configuration=${{ matrix.config }} -property:Platform=${{ matrix.platform }}
